smart_home/home/urls.py
from django.urls import path
from .views import land_detail, LandListView, viewIndex

urlpatterns = [
    path('', viewIndex, name='index'),
    path('<username>/home/', LandListView.as_view(), name='list_home'),
    path('<username>/land_detales/<int:house_id>/', land_detail, name='land_detail'),
]

smart_home/smart_home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('device/', include('device.urls')),
    path('', include('home.urls')),
    path('user/', include('django.contrib.auth.urls')),
    # path("404/", views.page_not_found, name='404'),
    # path("500/", views.server_error, name='500'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'user.views.page_not_found'
handler500 = 'user.views.server_error'
# handler403 = 'my_app_name.views.custom_permission_denied_view'
# handler400 = 'my_app_name.views.custom_bad_request_view'

smart_home/device/models.py
from tabnanny import verbose
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model
from django.forms import SlugField
User = get_user_model()


class SmartSystem(models.Model):
    """Системы умного дома"""
    name = models.CharField(max_length=100, verbose_name='Имя системы УД', unique=True)
    description = models.TextField(max_length=200, verbose_name='Описание системы УД')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='smart_sustems')

    class Meta:
        verbose_name = 'Система УД'
        verbose_name_plural = 'Системы УД'
        ordering = ['name']

    def __str__(self):
        return self.name

class Manufacturer(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование производителя', unique=True)
    description = models.TextField(max_length=500, verbose_name='Описание')
    site = models.URLField(max_length=100, verbose_name='Сайт компании')

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'
        ordering = ['title']
    
    def __str__(self):
        return self.title

class Output(models.Model):
    """Параметры выхода"""
    RELAY_NOC = 'Реле (NO C)'
    RELAY_NCC = 'Реле (NC C)'
    RELAY_NCCNO = 'Реле (NC C NO)'
    PWM = 'ШИМ выход'
    HZ = 'Неизвестно'

    TYPE_OUTPUT = [
        (RELAY_NOC, 'Реле NO/C'),
        (RELAY_NCC, 'Реле NC/C'),
        (RELAY_NCCNO, 'Реле NC/C/NO'),
        (PWM, 'ШИМ'),
        (HZ, 'ХЗ'),
    ]
    
    name = models.CharField(max_length=100, verbose_name='Наименование выхода', unique=True)
    type = models.CharField(max_length=50, choices=TYPE_OUTPUT, default=HZ)
    description = models.TextField(max_length=200, verbose_name='Описание выхода')
    voltage_ac = models.IntegerField(default=0, blank=True, null=True, verbose_name='Коммутируемое переменное напряжение')
    voltage_dc = models.IntegerField(default=0, blank=True, null=True, verbose_name='Коммутируемое постоянное напряжение')
    nominal_current = models.IntegerField(default=0, blank=True, null=True, verbose_name='Номинальный коммутируемый ток')
    maximal_current = models.IntegerField(default=0, blank=True, null=True, verbose_name='Максимальный коммутируемый ток')
    starting_current = models.IntegerField(default=0, blank=True, null=True, verbose_name='Пусковой ток')
    pwm_frequency = models.IntegerField(default=0, blank=True, null=True, verbose_name='Частота ШИМ')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='outputs')

    class Meta:
        verbose_name = 'Выход'
        verbose_name_plural = 'Выходы'
        ordering = ['name']

    def __str__(self):
        return f'{self.name} {self.voltage_ac}В {self.nominal_current}А(ном) {self.starting_current}А(старт)'


class Input(models.Model):
    """Параметры входа"""
    name = models.CharField(max_length=100, verbose_name='Наименование входа', unique=True)
    description = models.TextField(max_length=200, verbose_name='Описание входа')
    purpose = models.TextField(max_length=500, verbose_name='Назначение входа', null=True, blank=True)
    general_purpose = models.BooleanField(default=False, verbose_name='Вход общего назначения')
    counting_signals = models.BooleanField(default=False, verbose_name='Счет сигналов')
    frequency_measurement = models.BooleanField(default=False, verbose_name='Измерение частоты')
    direct_control = models.BooleanField(default=False, verbose_name='Прямое управление реле')
    mapping_matrix = models.BooleanField(default=False, verbose_name='Настройка с помощью mapping-матрицы')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='inputs')


    class Meta:
        verbose_name = 'Вход'
        verbose_name_plural = 'Входы'
        ordering = ['name']

    def __str__(self):
        return self.name


class Interface(models.Model):
    """Интерфейс"""
    name = models.CharField(max_length=100, verbose_name='Название интерфейса', unique=True)
    description = models.TextField(max_length=200, verbose_name='Описание интерфейса')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='interfaces')

    class Meta:
        verbose_name = 'Интерфейс'
        verbose_name_plural = 'Интерфейсы'
        ordering = ['name']

    def __str__(self):
        return self.name


class Device(models.Model):
    """SmartHome устройство"""
    image = models.ImageField(verbose_name='Изображение', upload_to='device/image/', default='device/image/default_device.jpg', blank=True, null=True)
    name = models.CharField(max_length=100, verbose_name='Название устрройства', unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="slug URL")
    short_description = models.TextField(max_length=200, verbose_name='Краткое описание')
    description = models.TextField(max_length=500, verbose_name='Полное описание')
    specific = models.ManyToManyField(SmartSystem, blank=True,  related_name='devices', verbose_name='К какой системе относится')
    input = models.ManyToManyField(
        Input,
        blank=True,
        verbose_name='Входы',
        related_name='devices_in',
        through='QuantityInput',
        through_fields=('device', 'pin',)
    )
    output = models.ManyToManyField(
        Output,
        blank=True,
        verbose_name='Выходы',
        related_name='devices_out',
        through='QuantityOutput',
        through_fields=('device', 'pin',)
    )
    interface = models.ManyToManyField(Interface, blank=True, verbose_name='Интерфейс', related_name='devices')
    unit = models.IntegerField(default=0, verbose_name='Количество юнитов занимаемое устройством')
    voltage = models.IntegerField(default=0, verbose_name='Напряжение питания В')
    current = models.FloatField(default=0, verbose_name='Потребление тока Вт')
    price = models.IntegerField(default=0, verbose_name='Цена Р')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='devices')
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=True, related_name='devices')

    
    class Meta:
        verbose_name = 'Smart Home Устройство'
        verbose_name_plural = 'Smart Home Устройства'
        ordering = ['name']

    def __str__(self):
        return self.name


class  QuantityOutput(models.Model):
    pin = models.ForeignKey(Output, on_delete=models.CASCADE, related_name='quantity_outputs')
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='quantity_outputs')
    quantity = models.IntegerField(
        null=True,
        blank=True,
        default=0,
        validators=[MinValueValidator(0, 'Минимальное значение 0')],
        verbose_name='Количество выходов'
    )
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['pin', 'device'], name='unicue_ingredient'
            ),
        ]


class  QuantityInput(models.Model):
    pin = models.ForeignKey(Input, on_delete=models.CASCADE, related_name='quantity_inputs')
    device = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='quantity_inputs')
    quantity = models.IntegerField(
        null=True,
        blank=True,
        default=0,
        validators=[MinValueValidator(0, 'Минимальное значение 0')],
        verbose_name='Количество входов'
    )

smart_home/templates/footer.html
<div class="jumbotron ">
    <div class="container-lg  mx-auto">
      <h1>О нас</h1>
      <p>Создание проекта умного дома
      </p>
      <p>Если вы заметили баги или хотите предложить как улушить функционал, заполните 
          форму <a href="#">здесь</a>, возможно я когда нибудь прочту вашу писанину и возможно отвечу, 
          хотите быстрого ответа на ваш вопрос или предложение, 
              пишите на какой нибудь мессенджер какой найдете. 
        
      <p>
        <a class="btn btn-primary" href="#" role="button">Пока не работает &raquo;</a>
      </p>
    </div>
  </div>

smart_home/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-fiolet">
    <div class="container-xl">
      <a class="navbar-brand" href="#">SMART HOME CONFIGURATOR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarsExample07XL">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Главная </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">О нас</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-toggle="dropdown" aria-expanded="false">Каталоги</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07XL">
              <a class="dropdown-item" href="#">Загородные дома</a>
              <a class="dropdown-item" href="#">Периферийное оборудование</a>
              <a class="dropdown-item" href="{% url "device_list" %}">Приборы УД</a>
              <a class="dropdown-item" href="#">Электрика</a>
            </div>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-toggle="dropdown" aria-expanded="false">Личный кабинет</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07XL">
              <a class="dropdown-item" href="#">Профиль</a>
              <a class="dropdown-item" href="{% url "list_home" user.username %}">Мои Умные Дома</a>
              <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Выход</a>
            </div>
          </li>
          <li>
            <a class="nav-link" href="#">{{ user.username }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Войти</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
  
  </div>
  

smart_home/templates/index.html
<!doctype html>
  <html lang="ru">
    <head>
      {% load static %}
      <!-- Required meta tags -->
      {% comment %} <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> {% endcomment %}
      <meta charset="utf-8">
      <meta content="text/html; charset=UTF-8; X-Content-Type-Options=sniffing" http-equiv="Content-Type" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
      
      
      <!--custom css & js-->
      {% block scripts %}{% endblock %}
      
      <link rel="stylesheet" href={% static 'css/style.css' %}>
      


      <style>
        .bg-fiolet {
          background-color: #024184 !important;
        }
      </style>
      <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
      <header>{% include 'header.html' %}</header>
      <main>
        <div class="container-lg">
        {% block content %}
          Контент не подвезли :(
        {% endblock %}
      

        </div>
      </main>
      <footer>{% include 'footer.html' %}</footer>
    </body>
</html>